### ISSUE TITLE
スクロール時にヘッダを画面上部に固定する機能の実装

### ISSUE THREAD

**Issue by kawayama** [kawayama/icss-2025-website#2]
## 機能概要
ユーザーがページをスクロールした際に、ヘッダー（ナビゲーションバー）を画面上部に固定表示する機能を実装します。

## 現状の課題
現在、ページをスクロールするとヘッダーも一緒にスクロールして見えなくなるため、ユーザーがナビゲーションにアクセスするには画面上部まで戻る必要があります。

## 期待される動作
- ユーザーがページをスクロールダウンしても、ヘッダーは画面上部に固定されたまま表示される
- ヘッダーは常に視認可能で、サイト内のどこからでもナビゲーションにアクセスできる
- モバイル表示でも正しく機能する

## 技術的な実装案
- CSSの `position: sticky` または `position: fixed` を使用
- スクロール位置に応じてヘッダーのスタイルを動的に変更（例：背景色の変更やシャドウの追加）
- 必要に応じてスクロールイベントリスナーを使用して挙動を制御

## 実装例
```css
.header {
  position: sticky;
  top: 0;
  z-index: 1000;
  background-color: rgba(255, 255, 255, 0.9); /* 半透明背景 */
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* スクロール時のシャドウ */
  transition: all 0.3s ease; /* スムーズな視覚効果 */
}
```

## ユーザー体験の向上点
- ナビゲーションの利便性が向上
- サイト内の移動がスムーズに
- 特に長いページ（タイムテーブルなど）での使いやすさが向上

## 優先度
中 - ユーザーエクスペリエンスを向上させる重要な機能
